[theme]
# shades of purple
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"

[server]
# port = 8501
# headless = true
# for local development:
runOnSave = true
# if running docker on windows host:
# fileWatcherType = "poll"
